### ISSUE TITLE
Solar System Data

### ISSUE THREAD

**Issue by PhDaveMil** [itteerde/ep2eFVTT#15]
Specifically, I need a program that will query me for the name of two planets, a date, and that will in turn provide their distance in AU, miles, and the time it would take light to travel between the two of them.

**Comment by itteerde** [comment]
```wl
d=Entity["Planet", "Jupiter"][EntityProperty["Planet", "DistanceFromEarth", {"Date" -> DateObject[{2525, 1, 1}]}]];
d/(Quantity[300000,"Kilometers"]/Quantity[1,"Seconds"])
```
![image](https://github.com/itteerde/ep2eFVTT/assets/8367477/0d0a305a-893c-4be0-af03-9b6a6a8949fb)

**Comment by itteerde** [comment]
Communication time (or any other time taken at constant speed) with the movement of the destination during transit ignored (which certainly is good enough for light speed with in the solar system) is relatively simple. You mentioned physical travel however. So there will be "ship" travel? Depending on what there will be in the game different tools have different utility. So I need to know what beyond communication at the speed of light in vacuum is needed in order to search for, pick and provide the tools.

**Comment by PhDaveMil** [comment]
Space travel does happen. We approximate travel times on the basis of reality. Feel free to model the physics as you see fit.

**Comment by itteerde** [comment]
* `Antimatter Drive` seems to be the propulsion system. So The energy available is possible to approximate somewhat. Ignoring the containment the energy per mass can be estimated well enough, too. How we get from there to impulse, I still need to figure out. And then we need some simple estimates instead of dealing with real trajectories -- unless we want to make it into a science project, which would not get us anything learning post graduate methods in physics.

**Comment by itteerde** [comment]
done
